modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mixins]]
config = "cryptand.mixins.json"

[[mixins]]
config = "cryptand.core.mixins.json"

[[mixins]]
config = "cryptand.powergrid.mixins.json"

[[mixins]]
config = "cryptand.railway.mixins.json"

[[mixins]]
config = "cryptand.cee.mixins.json"

[[mixins]]
config = "cryptand.sable.mixins.json"

[[mixins]]
config = "cryptand.create.mixins.json"

[[mixins]]
config = "cryptand.aeronautics.mixins.json"

[[mixins]]
config = "cryptand.pipez.mixins.json"

[[mixins]]
config = "cryptand.waterphysics.mixins.json"

[[mixins]]
config = "cryptand.sable.core.mixins.json"

[[mixins]]
config = "cryptand.sable.sable.mixins.json"

[[mixins]]
config = "cryptand.sable.aeronautics.mixins.json"

[[mixins]]
config = "cryptand.sable.simulated.mixins.json"

[[mixins]]
config = "cryptand.sable.offroad.mixins.json"

[[mixins]]
config = "cryptand.sable.tire.mixins.json"

[[mixins]]
config = "cryptand.sable.schematicapi.mixins.json"

[[mixins]]
config = "cryptand.sable.cee.mixins.json"

[[mixins]]
config = "cryptand.sable.powergrid.mixins.json"

[[mixins]]
config = "cryptand.sable.debug.mixins.json"

[[mods]]
modId = "cryptand"
version = "${version}"
displayName = "Cryptand Mod"
logoFile = "icon.png"
authors = "HalfDragonFox"
description = '''
Cryptand Mod - Multi-threading optimization for Create: Power Grid
'''

[[dependencies.cryptand]]
modId = "neoforge"
mandatory = true
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cryptand]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cryptand]]
modId = "architectury"
mandatory = true
versionRange = "[13,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cryptand]]
modId = "create"
mandatory = true
versionRange = "[6.0,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.cryptand]]
modId = "powergrid"
mandatory = true
versionRange = "[0.5.5.1,)"
ordering = "AFTER"
side = "BOTH"
